import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { Menu } from "@/shared/components/Menu";
import { Pie } from "@/shared/components/Pie";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-w-[1300px]">
        <div>
          <Menu />
        </div>

        {children}
        <Pie />
      </body>
    </html>
  );
}
